# The GLFW backend includes GLFW's headers: LIBS=glfw also builds libglfw.m
# (which stages them) first, and passes -lglfw on to libimgui's consumers.
LIB=imgui
LIB_SHARED=NO
WARN=none
LIBS=glfw
.include "mk.lib.mk"
